// Code generated by go-swagger; DO NOT EDIT.

package repositories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetRepositoryBranchesParams creates a new GetRepositoryBranchesParams object
// no default values defined in spec.
func NewGetRepositoryBranchesParams() GetRepositoryBranchesParams {

	return GetRepositoryBranchesParams{}
}

// GetRepositoryBranchesParams contains all the bound params for the get repository branches operation
// typically these are obtained from a http.Request
//
// swagger:parameters getRepositoryBranches
type GetRepositoryBranchesParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The repository's name
	  Required: true
	  In: path
	*/
	Name string
	/*The owner's username
	  Required: true
	  In: path
	*/
	Owner string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetRepositoryBranchesParams() beforehand.
func (o *GetRepositoryBranchesParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rName, rhkName, _ := route.Params.GetOK("name")
	if err := o.bindName(rName, rhkName, route.Formats); err != nil {
		res = append(res, err)
	}

	rOwner, rhkOwner, _ := route.Params.GetOK("owner")
	if err := o.bindOwner(rOwner, rhkOwner, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindName binds and validates parameter Name from path.
func (o *GetRepositoryBranchesParams) bindName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.Name = raw

	return nil
}

// bindOwner binds and validates parameter Owner from path.
func (o *GetRepositoryBranchesParams) bindOwner(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.Owner = raw

	return nil
}
