// Code generated by go-swagger; DO NOT EDIT.

package repositories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetRepositoryTreeParams creates a new GetRepositoryTreeParams object
// no default values defined in spec.
func NewGetRepositoryTreeParams() GetRepositoryTreeParams {

	return GetRepositoryTreeParams{}
}

// GetRepositoryTreeParams contains all the bound params for the get repository tree operation
// typically these are obtained from a http.Request
//
// swagger:parameters getRepositoryTree
type GetRepositoryTreeParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The repository's name
	  Required: true
	  In: path
	*/
	Name string
	/*The owner's username
	  Required: true
	  In: path
	*/
	Owner string
	/*The path for the tree
	  In: query
	*/
	Path *string
	/*The ref for the tree
	  In: query
	*/
	Ref *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetRepositoryTreeParams() beforehand.
func (o *GetRepositoryTreeParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	rName, rhkName, _ := route.Params.GetOK("name")
	if err := o.bindName(rName, rhkName, route.Formats); err != nil {
		res = append(res, err)
	}

	rOwner, rhkOwner, _ := route.Params.GetOK("owner")
	if err := o.bindOwner(rOwner, rhkOwner, route.Formats); err != nil {
		res = append(res, err)
	}

	qPath, qhkPath, _ := qs.GetOK("path")
	if err := o.bindPath(qPath, qhkPath, route.Formats); err != nil {
		res = append(res, err)
	}

	qRef, qhkRef, _ := qs.GetOK("ref")
	if err := o.bindRef(qRef, qhkRef, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindName binds and validates parameter Name from path.
func (o *GetRepositoryTreeParams) bindName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.Name = raw

	return nil
}

// bindOwner binds and validates parameter Owner from path.
func (o *GetRepositoryTreeParams) bindOwner(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.Owner = raw

	return nil
}

// bindPath binds and validates parameter Path from query.
func (o *GetRepositoryTreeParams) bindPath(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.Path = &raw

	return nil
}

// bindRef binds and validates parameter Ref from query.
func (o *GetRepositoryTreeParams) bindRef(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.Ref = &raw

	return nil
}
