// Code generated by go-swagger; DO NOT EDIT.

package repositories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetRepositoryCommitsHandlerFunc turns a function with the right signature into a get repository commits handler
type GetRepositoryCommitsHandlerFunc func(GetRepositoryCommitsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetRepositoryCommitsHandlerFunc) Handle(params GetRepositoryCommitsParams) middleware.Responder {
	return fn(params)
}

// GetRepositoryCommitsHandler interface for that can handle valid get repository commits params
type GetRepositoryCommitsHandler interface {
	Handle(GetRepositoryCommitsParams) middleware.Responder
}

// NewGetRepositoryCommits creates a new http.Handler for the get repository commits operation
func NewGetRepositoryCommits(ctx *middleware.Context, handler GetRepositoryCommitsHandler) *GetRepositoryCommits {
	return &GetRepositoryCommits{Context: ctx, Handler: handler}
}

/*GetRepositoryCommits swagger:route GET /repositories/{owner}/{name}/commits repositories getRepositoryCommits

Get the commits for a repository

*/
type GetRepositoryCommits struct {
	Context *middleware.Context
	Handler GetRepositoryCommitsHandler
}

func (o *GetRepositoryCommits) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetRepositoryCommitsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
