// Code generated by go-swagger; DO NOT EDIT.

package repositories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetRepositoryBranchesHandlerFunc turns a function with the right signature into a get repository branches handler
type GetRepositoryBranchesHandlerFunc func(GetRepositoryBranchesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetRepositoryBranchesHandlerFunc) Handle(params GetRepositoryBranchesParams) middleware.Responder {
	return fn(params)
}

// GetRepositoryBranchesHandler interface for that can handle valid get repository branches params
type GetRepositoryBranchesHandler interface {
	Handle(GetRepositoryBranchesParams) middleware.Responder
}

// NewGetRepositoryBranches creates a new http.Handler for the get repository branches operation
func NewGetRepositoryBranches(ctx *middleware.Context, handler GetRepositoryBranchesHandler) *GetRepositoryBranches {
	return &GetRepositoryBranches{Context: ctx, Handler: handler}
}

/*GetRepositoryBranches swagger:route GET /repositories/{owner}/{name}/branches repositories getRepositoryBranches

Get all branches of a repository

*/
type GetRepositoryBranches struct {
	Context *middleware.Context
	Handler GetRepositoryBranchesHandler
}

func (o *GetRepositoryBranches) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetRepositoryBranchesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
