// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/storage/storage.proto

package storage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CommitCountRequest struct {
	// Respository ID
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ref                  string   `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitCountRequest) Reset()         { *m = CommitCountRequest{} }
func (m *CommitCountRequest) String() string { return proto.CompactTextString(m) }
func (*CommitCountRequest) ProtoMessage()    {}
func (*CommitCountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_d2d996bf7f0ca16a, []int{0}
}
func (m *CommitCountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitCountRequest.Unmarshal(m, b)
}
func (m *CommitCountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitCountRequest.Marshal(b, m, deterministic)
}
func (dst *CommitCountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitCountRequest.Merge(dst, src)
}
func (m *CommitCountRequest) XXX_Size() int {
	return xxx_messageInfo_CommitCountRequest.Size(m)
}
func (m *CommitCountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitCountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommitCountRequest proto.InternalMessageInfo

func (m *CommitCountRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CommitCountRequest) GetRef() string {
	if m != nil {
		return m.Ref
	}
	return ""
}

type CommitListRequest struct {
	// Respository ID
	Id  string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ref string `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	// limit amount of commits returned
	Limit int64 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	// skip N*limit commits
	Skip                 int64    `protobuf:"varint,4,opt,name=skip,proto3" json:"skip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitListRequest) Reset()         { *m = CommitListRequest{} }
func (m *CommitListRequest) String() string { return proto.CompactTextString(m) }
func (*CommitListRequest) ProtoMessage()    {}
func (*CommitListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_d2d996bf7f0ca16a, []int{1}
}
func (m *CommitListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitListRequest.Unmarshal(m, b)
}
func (m *CommitListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitListRequest.Marshal(b, m, deterministic)
}
func (dst *CommitListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitListRequest.Merge(dst, src)
}
func (m *CommitListRequest) XXX_Size() int {
	return xxx_messageInfo_CommitListRequest.Size(m)
}
func (m *CommitListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommitListRequest proto.InternalMessageInfo

func (m *CommitListRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CommitListRequest) GetRef() string {
	if m != nil {
		return m.Ref
	}
	return ""
}

func (m *CommitListRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *CommitListRequest) GetSkip() int64 {
	if m != nil {
		return m.Skip
	}
	return 0
}

type CommitListResponse struct {
	Commits              []*CommitResponse `protobuf:"bytes,1,rep,name=commits,proto3" json:"commits,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CommitListResponse) Reset()         { *m = CommitListResponse{} }
func (m *CommitListResponse) String() string { return proto.CompactTextString(m) }
func (*CommitListResponse) ProtoMessage()    {}
func (*CommitListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_d2d996bf7f0ca16a, []int{2}
}
func (m *CommitListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitListResponse.Unmarshal(m, b)
}
func (m *CommitListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitListResponse.Marshal(b, m, deterministic)
}
func (dst *CommitListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitListResponse.Merge(dst, src)
}
func (m *CommitListResponse) XXX_Size() int {
	return xxx_messageInfo_CommitListResponse.Size(m)
}
func (m *CommitListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommitListResponse proto.InternalMessageInfo

func (m *CommitListResponse) GetCommits() []*CommitResponse {
	if m != nil {
		return m.Commits
	}
	return nil
}

type CommitCountResponse struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitCountResponse) Reset()         { *m = CommitCountResponse{} }
func (m *CommitCountResponse) String() string { return proto.CompactTextString(m) }
func (*CommitCountResponse) ProtoMessage()    {}
func (*CommitCountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_d2d996bf7f0ca16a, []int{3}
}
func (m *CommitCountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitCountResponse.Unmarshal(m, b)
}
func (m *CommitCountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitCountResponse.Marshal(b, m, deterministic)
}
func (dst *CommitCountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitCountResponse.Merge(dst, src)
}
func (m *CommitCountResponse) XXX_Size() int {
	return xxx_messageInfo_CommitCountResponse.Size(m)
}
func (m *CommitCountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitCountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommitCountResponse proto.InternalMessageInfo

func (m *CommitCountResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

// GRE == gRPC Remote Execution
type GRERequest struct {
	// Repository ID, must be present in the first message.
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Stdin                []byte   `protobuf:"bytes,2,opt,name=stdin,proto3" json:"stdin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GRERequest) Reset()         { *m = GRERequest{} }
func (m *GRERequest) String() string { return proto.CompactTextString(m) }
func (*GRERequest) ProtoMessage()    {}
func (*GRERequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_d2d996bf7f0ca16a, []int{4}
}
func (m *GRERequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GRERequest.Unmarshal(m, b)
}
func (m *GRERequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GRERequest.Marshal(b, m, deterministic)
}
func (dst *GRERequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GRERequest.Merge(dst, src)
}
func (m *GRERequest) XXX_Size() int {
	return xxx_messageInfo_GRERequest.Size(m)
}
func (m *GRERequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GRERequest.DiscardUnknown(m)
}

var xxx_messageInfo_GRERequest proto.InternalMessageInfo

func (m *GRERequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GRERequest) GetStdin() []byte {
	if m != nil {
		return m.Stdin
	}
	return nil
}

type GREResponse struct {
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr []byte `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	// ONLY sent in the last message.
	ExitCode             *GREExitCode `protobuf:"bytes,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GREResponse) Reset()         { *m = GREResponse{} }
func (m *GREResponse) String() string { return proto.CompactTextString(m) }
func (*GREResponse) ProtoMessage()    {}
func (*GREResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_d2d996bf7f0ca16a, []int{5}
}
func (m *GREResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GREResponse.Unmarshal(m, b)
}
func (m *GREResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GREResponse.Marshal(b, m, deterministic)
}
func (dst *GREResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GREResponse.Merge(dst, src)
}
func (m *GREResponse) XXX_Size() int {
	return xxx_messageInfo_GREResponse.Size(m)
}
func (m *GREResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GREResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GREResponse proto.InternalMessageInfo

func (m *GREResponse) GetStdout() []byte {
	if m != nil {
		return m.Stdout
	}
	return nil
}

func (m *GREResponse) GetStderr() []byte {
	if m != nil {
		return m.Stderr
	}
	return nil
}

func (m *GREResponse) GetExitCode() *GREExitCode {
	if m != nil {
		return m.ExitCode
	}
	return nil
}

type GREExitCode struct {
	ExitCode             int32    `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GREExitCode) Reset()         { *m = GREExitCode{} }
func (m *GREExitCode) String() string { return proto.CompactTextString(m) }
func (*GREExitCode) ProtoMessage()    {}
func (*GREExitCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_d2d996bf7f0ca16a, []int{6}
}
func (m *GREExitCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GREExitCode.Unmarshal(m, b)
}
func (m *GREExitCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GREExitCode.Marshal(b, m, deterministic)
}
func (dst *GREExitCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GREExitCode.Merge(dst, src)
}
func (m *GREExitCode) XXX_Size() int {
	return xxx_messageInfo_GREExitCode.Size(m)
}
func (m *GREExitCode) XXX_DiscardUnknown() {
	xxx_messageInfo_GREExitCode.DiscardUnknown(m)
}

var xxx_messageInfo_GREExitCode proto.InternalMessageInfo

func (m *GREExitCode) GetExitCode() int32 {
	if m != nil {
		return m.ExitCode
	}
	return 0
}

type CreateRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_d2d996bf7f0ca16a, []int{7}
}
func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (dst *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(dst, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SetDescriptionRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetDescriptionRequest) Reset()         { *m = SetDescriptionRequest{} }
func (m *SetDescriptionRequest) String() string { return proto.CompactTextString(m) }
func (*SetDescriptionRequest) ProtoMessage()    {}
func (*SetDescriptionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_d2d996bf7f0ca16a, []int{8}
}
func (m *SetDescriptionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetDescriptionRequest.Unmarshal(m, b)
}
func (m *SetDescriptionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetDescriptionRequest.Marshal(b, m, deterministic)
}
func (dst *SetDescriptionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetDescriptionRequest.Merge(dst, src)
}
func (m *SetDescriptionRequest) XXX_Size() int {
	return xxx_messageInfo_SetDescriptionRequest.Size(m)
}
func (m *SetDescriptionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetDescriptionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetDescriptionRequest proto.InternalMessageInfo

func (m *SetDescriptionRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SetDescriptionRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type BranchesRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BranchesRequest) Reset()         { *m = BranchesRequest{} }
func (m *BranchesRequest) String() string { return proto.CompactTextString(m) }
func (*BranchesRequest) ProtoMessage()    {}
func (*BranchesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_d2d996bf7f0ca16a, []int{9}
}
func (m *BranchesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BranchesRequest.Unmarshal(m, b)
}
func (m *BranchesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BranchesRequest.Marshal(b, m, deterministic)
}
func (dst *BranchesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BranchesRequest.Merge(dst, src)
}
func (m *BranchesRequest) XXX_Size() int {
	return xxx_messageInfo_BranchesRequest.Size(m)
}
func (m *BranchesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BranchesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BranchesRequest proto.InternalMessageInfo

func (m *BranchesRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type BranchResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Sha1                 string   `protobuf:"bytes,2,opt,name=sha1,proto3" json:"sha1,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BranchResponse) Reset()         { *m = BranchResponse{} }
func (m *BranchResponse) String() string { return proto.CompactTextString(m) }
func (*BranchResponse) ProtoMessage()    {}
func (*BranchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_d2d996bf7f0ca16a, []int{10}
}
func (m *BranchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BranchResponse.Unmarshal(m, b)
}
func (m *BranchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BranchResponse.Marshal(b, m, deterministic)
}
func (dst *BranchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BranchResponse.Merge(dst, src)
}
func (m *BranchResponse) XXX_Size() int {
	return xxx_messageInfo_BranchResponse.Size(m)
}
func (m *BranchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BranchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BranchResponse proto.InternalMessageInfo

func (m *BranchResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BranchResponse) GetSha1() string {
	if m != nil {
		return m.Sha1
	}
	return ""
}

func (m *BranchResponse) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type BranchesResponse struct {
	Branch               []*BranchResponse `protobuf:"bytes,1,rep,name=branch,proto3" json:"branch,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BranchesResponse) Reset()         { *m = BranchesResponse{} }
func (m *BranchesResponse) String() string { return proto.CompactTextString(m) }
func (*BranchesResponse) ProtoMessage()    {}
func (*BranchesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_d2d996bf7f0ca16a, []int{11}
}
func (m *BranchesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BranchesResponse.Unmarshal(m, b)
}
func (m *BranchesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BranchesResponse.Marshal(b, m, deterministic)
}
func (dst *BranchesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BranchesResponse.Merge(dst, src)
}
func (m *BranchesResponse) XXX_Size() int {
	return xxx_messageInfo_BranchesResponse.Size(m)
}
func (m *BranchesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BranchesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BranchesResponse proto.InternalMessageInfo

func (m *BranchesResponse) GetBranch() []*BranchResponse {
	if m != nil {
		return m.Branch
	}
	return nil
}

type CommitRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ref                  string   `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitRequest) Reset()         { *m = CommitRequest{} }
func (m *CommitRequest) String() string { return proto.CompactTextString(m) }
func (*CommitRequest) ProtoMessage()    {}
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_d2d996bf7f0ca16a, []int{12}
}
func (m *CommitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitRequest.Unmarshal(m, b)
}
func (m *CommitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitRequest.Marshal(b, m, deterministic)
}
func (dst *CommitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitRequest.Merge(dst, src)
}
func (m *CommitRequest) XXX_Size() int {
	return xxx_messageInfo_CommitRequest.Size(m)
}
func (m *CommitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommitRequest proto.InternalMessageInfo

func (m *CommitRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CommitRequest) GetRef() string {
	if m != nil {
		return m.Ref
	}
	return ""
}

type CommitResponse struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Tree                 string   `protobuf:"bytes,2,opt,name=Tree,proto3" json:"Tree,omitempty"`
	Parent               string   `protobuf:"bytes,3,opt,name=Parent,proto3" json:"Parent,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=Message,proto3" json:"Message,omitempty"`
	Author               string   `protobuf:"bytes,5,opt,name=Author,proto3" json:"Author,omitempty"`
	AuthorEmail          string   `protobuf:"bytes,6,opt,name=AuthorEmail,proto3" json:"AuthorEmail,omitempty"`
	AuthorDate           int64    `protobuf:"varint,7,opt,name=AuthorDate,proto3" json:"AuthorDate,omitempty"`
	Committer            string   `protobuf:"bytes,8,opt,name=Committer,proto3" json:"Committer,omitempty"`
	CommitterEmail       string   `protobuf:"bytes,9,opt,name=CommitterEmail,proto3" json:"CommitterEmail,omitempty"`
	CommitterDate        int64    `protobuf:"varint,10,opt,name=CommitterDate,proto3" json:"CommitterDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitResponse) Reset()         { *m = CommitResponse{} }
func (m *CommitResponse) String() string { return proto.CompactTextString(m) }
func (*CommitResponse) ProtoMessage()    {}
func (*CommitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_d2d996bf7f0ca16a, []int{13}
}
func (m *CommitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitResponse.Unmarshal(m, b)
}
func (m *CommitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitResponse.Marshal(b, m, deterministic)
}
func (dst *CommitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitResponse.Merge(dst, src)
}
func (m *CommitResponse) XXX_Size() int {
	return xxx_messageInfo_CommitResponse.Size(m)
}
func (m *CommitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommitResponse proto.InternalMessageInfo

func (m *CommitResponse) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *CommitResponse) GetTree() string {
	if m != nil {
		return m.Tree
	}
	return ""
}

func (m *CommitResponse) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *CommitResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CommitResponse) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *CommitResponse) GetAuthorEmail() string {
	if m != nil {
		return m.AuthorEmail
	}
	return ""
}

func (m *CommitResponse) GetAuthorDate() int64 {
	if m != nil {
		return m.AuthorDate
	}
	return 0
}

func (m *CommitResponse) GetCommitter() string {
	if m != nil {
		return m.Committer
	}
	return ""
}

func (m *CommitResponse) GetCommitterEmail() string {
	if m != nil {
		return m.CommitterEmail
	}
	return ""
}

func (m *CommitResponse) GetCommitterDate() int64 {
	if m != nil {
		return m.CommitterDate
	}
	return 0
}

type TreeRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ref                  string   `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	Path                 string   `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TreeRequest) Reset()         { *m = TreeRequest{} }
func (m *TreeRequest) String() string { return proto.CompactTextString(m) }
func (*TreeRequest) ProtoMessage()    {}
func (*TreeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_d2d996bf7f0ca16a, []int{14}
}
func (m *TreeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TreeRequest.Unmarshal(m, b)
}
func (m *TreeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TreeRequest.Marshal(b, m, deterministic)
}
func (dst *TreeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TreeRequest.Merge(dst, src)
}
func (m *TreeRequest) XXX_Size() int {
	return xxx_messageInfo_TreeRequest.Size(m)
}
func (m *TreeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TreeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TreeRequest proto.InternalMessageInfo

func (m *TreeRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TreeRequest) GetRef() string {
	if m != nil {
		return m.Ref
	}
	return ""
}

func (m *TreeRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type TreeEntryResponse struct {
	Mode                 string   `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Object               string   `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
	Path                 string   `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TreeEntryResponse) Reset()         { *m = TreeEntryResponse{} }
func (m *TreeEntryResponse) String() string { return proto.CompactTextString(m) }
func (*TreeEntryResponse) ProtoMessage()    {}
func (*TreeEntryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_d2d996bf7f0ca16a, []int{15}
}
func (m *TreeEntryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TreeEntryResponse.Unmarshal(m, b)
}
func (m *TreeEntryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TreeEntryResponse.Marshal(b, m, deterministic)
}
func (dst *TreeEntryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TreeEntryResponse.Merge(dst, src)
}
func (m *TreeEntryResponse) XXX_Size() int {
	return xxx_messageInfo_TreeEntryResponse.Size(m)
}
func (m *TreeEntryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TreeEntryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TreeEntryResponse proto.InternalMessageInfo

func (m *TreeEntryResponse) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

func (m *TreeEntryResponse) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *TreeEntryResponse) GetObject() string {
	if m != nil {
		return m.Object
	}
	return ""
}

func (m *TreeEntryResponse) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type TreeResponse struct {
	TreeEntries          []*TreeEntryResponse `protobuf:"bytes,1,rep,name=treeEntries,proto3" json:"treeEntries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TreeResponse) Reset()         { *m = TreeResponse{} }
func (m *TreeResponse) String() string { return proto.CompactTextString(m) }
func (*TreeResponse) ProtoMessage()    {}
func (*TreeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_d2d996bf7f0ca16a, []int{16}
}
func (m *TreeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TreeResponse.Unmarshal(m, b)
}
func (m *TreeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TreeResponse.Marshal(b, m, deterministic)
}
func (dst *TreeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TreeResponse.Merge(dst, src)
}
func (m *TreeResponse) XXX_Size() int {
	return xxx_messageInfo_TreeResponse.Size(m)
}
func (m *TreeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TreeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TreeResponse proto.InternalMessageInfo

func (m *TreeResponse) GetTreeEntries() []*TreeEntryResponse {
	if m != nil {
		return m.TreeEntries
	}
	return nil
}

func init() {
	proto.RegisterType((*CommitCountRequest)(nil), "storage.CommitCountRequest")
	proto.RegisterType((*CommitListRequest)(nil), "storage.CommitListRequest")
	proto.RegisterType((*CommitListResponse)(nil), "storage.CommitListResponse")
	proto.RegisterType((*CommitCountResponse)(nil), "storage.CommitCountResponse")
	proto.RegisterType((*GRERequest)(nil), "storage.GRERequest")
	proto.RegisterType((*GREResponse)(nil), "storage.GREResponse")
	proto.RegisterType((*GREExitCode)(nil), "storage.GREExitCode")
	proto.RegisterType((*CreateRequest)(nil), "storage.CreateRequest")
	proto.RegisterType((*SetDescriptionRequest)(nil), "storage.SetDescriptionRequest")
	proto.RegisterType((*BranchesRequest)(nil), "storage.BranchesRequest")
	proto.RegisterType((*BranchResponse)(nil), "storage.BranchResponse")
	proto.RegisterType((*BranchesResponse)(nil), "storage.BranchesResponse")
	proto.RegisterType((*CommitRequest)(nil), "storage.CommitRequest")
	proto.RegisterType((*CommitResponse)(nil), "storage.CommitResponse")
	proto.RegisterType((*TreeRequest)(nil), "storage.TreeRequest")
	proto.RegisterType((*TreeEntryResponse)(nil), "storage.TreeEntryResponse")
	proto.RegisterType((*TreeResponse)(nil), "storage.TreeResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RepositoryClient is the client API for Repository service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RepositoryClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	SetDescriptions(ctx context.Context, in *SetDescriptionRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	Tree(ctx context.Context, in *TreeRequest, opts ...grpc.CallOption) (*TreeResponse, error)
}

type repositoryClient struct {
	cc *grpc.ClientConn
}

func NewRepositoryClient(cc *grpc.ClientConn) RepositoryClient {
	return &repositoryClient{cc}
}

func (c *repositoryClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/storage.Repository/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoryClient) SetDescriptions(ctx context.Context, in *SetDescriptionRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/storage.Repository/SetDescriptions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoryClient) Tree(ctx context.Context, in *TreeRequest, opts ...grpc.CallOption) (*TreeResponse, error) {
	out := new(TreeResponse)
	err := c.cc.Invoke(ctx, "/storage.Repository/Tree", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RepositoryServer is the server API for Repository service.
type RepositoryServer interface {
	Create(context.Context, *CreateRequest) (*empty.Empty, error)
	SetDescriptions(context.Context, *SetDescriptionRequest) (*empty.Empty, error)
	Tree(context.Context, *TreeRequest) (*TreeResponse, error)
}

func RegisterRepositoryServer(s *grpc.Server, srv RepositoryServer) {
	s.RegisterService(&_Repository_serviceDesc, srv)
}

func _Repository_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.Repository/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Repository_SetDescriptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDescriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServer).SetDescriptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.Repository/SetDescriptions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServer).SetDescriptions(ctx, req.(*SetDescriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Repository_Tree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServer).Tree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.Repository/Tree",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServer).Tree(ctx, req.(*TreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Repository_serviceDesc = grpc.ServiceDesc{
	ServiceName: "storage.Repository",
	HandlerType: (*RepositoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Repository_Create_Handler,
		},
		{
			MethodName: "SetDescriptions",
			Handler:    _Repository_SetDescriptions_Handler,
		},
		{
			MethodName: "Tree",
			Handler:    _Repository_Tree_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/storage/storage.proto",
}

// BranchClient is the client API for Branch service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BranchClient interface {
	List(ctx context.Context, in *BranchesRequest, opts ...grpc.CallOption) (*BranchesResponse, error)
}

type branchClient struct {
	cc *grpc.ClientConn
}

func NewBranchClient(cc *grpc.ClientConn) BranchClient {
	return &branchClient{cc}
}

func (c *branchClient) List(ctx context.Context, in *BranchesRequest, opts ...grpc.CallOption) (*BranchesResponse, error) {
	out := new(BranchesResponse)
	err := c.cc.Invoke(ctx, "/storage.Branch/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BranchServer is the server API for Branch service.
type BranchServer interface {
	List(context.Context, *BranchesRequest) (*BranchesResponse, error)
}

func RegisterBranchServer(s *grpc.Server, srv BranchServer) {
	s.RegisterService(&_Branch_serviceDesc, srv)
}

func _Branch_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BranchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BranchServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.Branch/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BranchServer).List(ctx, req.(*BranchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Branch_serviceDesc = grpc.ServiceDesc{
	ServiceName: "storage.Branch",
	HandlerType: (*BranchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Branch_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/storage/storage.proto",
}

// CommitClient is the client API for Commit service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommitClient interface {
	Count(ctx context.Context, in *CommitCountRequest, opts ...grpc.CallOption) (*CommitCountResponse, error)
	List(ctx context.Context, in *CommitListRequest, opts ...grpc.CallOption) (Commit_ListClient, error)
	Get(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error)
}

type commitClient struct {
	cc *grpc.ClientConn
}

func NewCommitClient(cc *grpc.ClientConn) CommitClient {
	return &commitClient{cc}
}

func (c *commitClient) Count(ctx context.Context, in *CommitCountRequest, opts ...grpc.CallOption) (*CommitCountResponse, error) {
	out := new(CommitCountResponse)
	err := c.cc.Invoke(ctx, "/storage.Commit/Count", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commitClient) List(ctx context.Context, in *CommitListRequest, opts ...grpc.CallOption) (Commit_ListClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Commit_serviceDesc.Streams[0], "/storage.Commit/List", opts...)
	if err != nil {
		return nil, err
	}
	x := &commitListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Commit_ListClient interface {
	Recv() (*CommitListResponse, error)
	grpc.ClientStream
}

type commitListClient struct {
	grpc.ClientStream
}

func (x *commitListClient) Recv() (*CommitListResponse, error) {
	m := new(CommitListResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *commitClient) Get(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error) {
	out := new(CommitResponse)
	err := c.cc.Invoke(ctx, "/storage.Commit/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommitServer is the server API for Commit service.
type CommitServer interface {
	Count(context.Context, *CommitCountRequest) (*CommitCountResponse, error)
	List(*CommitListRequest, Commit_ListServer) error
	Get(context.Context, *CommitRequest) (*CommitResponse, error)
}

func RegisterCommitServer(s *grpc.Server, srv CommitServer) {
	s.RegisterService(&_Commit_serviceDesc, srv)
}

func _Commit_Count_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommitServer).Count(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.Commit/Count",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommitServer).Count(ctx, req.(*CommitCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Commit_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CommitListRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CommitServer).List(m, &commitListServer{stream})
}

type Commit_ListServer interface {
	Send(*CommitListResponse) error
	grpc.ServerStream
}

type commitListServer struct {
	grpc.ServerStream
}

func (x *commitListServer) Send(m *CommitListResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Commit_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommitServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.Commit/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommitServer).Get(ctx, req.(*CommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Commit_serviceDesc = grpc.ServiceDesc{
	ServiceName: "storage.Commit",
	HandlerType: (*CommitServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Count",
			Handler:    _Commit_Count_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Commit_Get_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "List",
			Handler:       _Commit_List_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/storage/storage.proto",
}

// SSHClient is the client API for SSH service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SSHClient interface {
	UploadPack(ctx context.Context, opts ...grpc.CallOption) (SSH_UploadPackClient, error)
	ReceivePack(ctx context.Context, opts ...grpc.CallOption) (SSH_ReceivePackClient, error)
}

type sSHClient struct {
	cc *grpc.ClientConn
}

func NewSSHClient(cc *grpc.ClientConn) SSHClient {
	return &sSHClient{cc}
}

func (c *sSHClient) UploadPack(ctx context.Context, opts ...grpc.CallOption) (SSH_UploadPackClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SSH_serviceDesc.Streams[0], "/storage.SSH/UploadPack", opts...)
	if err != nil {
		return nil, err
	}
	x := &sSHUploadPackClient{stream}
	return x, nil
}

type SSH_UploadPackClient interface {
	Send(*GRERequest) error
	Recv() (*GREResponse, error)
	grpc.ClientStream
}

type sSHUploadPackClient struct {
	grpc.ClientStream
}

func (x *sSHUploadPackClient) Send(m *GRERequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *sSHUploadPackClient) Recv() (*GREResponse, error) {
	m := new(GREResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sSHClient) ReceivePack(ctx context.Context, opts ...grpc.CallOption) (SSH_ReceivePackClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SSH_serviceDesc.Streams[1], "/storage.SSH/ReceivePack", opts...)
	if err != nil {
		return nil, err
	}
	x := &sSHReceivePackClient{stream}
	return x, nil
}

type SSH_ReceivePackClient interface {
	Send(*GRERequest) error
	Recv() (*GREResponse, error)
	grpc.ClientStream
}

type sSHReceivePackClient struct {
	grpc.ClientStream
}

func (x *sSHReceivePackClient) Send(m *GRERequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *sSHReceivePackClient) Recv() (*GREResponse, error) {
	m := new(GREResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SSHServer is the server API for SSH service.
type SSHServer interface {
	UploadPack(SSH_UploadPackServer) error
	ReceivePack(SSH_ReceivePackServer) error
}

func RegisterSSHServer(s *grpc.Server, srv SSHServer) {
	s.RegisterService(&_SSH_serviceDesc, srv)
}

func _SSH_UploadPack_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SSHServer).UploadPack(&sSHUploadPackServer{stream})
}

type SSH_UploadPackServer interface {
	Send(*GREResponse) error
	Recv() (*GRERequest, error)
	grpc.ServerStream
}

type sSHUploadPackServer struct {
	grpc.ServerStream
}

func (x *sSHUploadPackServer) Send(m *GREResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *sSHUploadPackServer) Recv() (*GRERequest, error) {
	m := new(GRERequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _SSH_ReceivePack_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SSHServer).ReceivePack(&sSHReceivePackServer{stream})
}

type SSH_ReceivePackServer interface {
	Send(*GREResponse) error
	Recv() (*GRERequest, error)
	grpc.ServerStream
}

type sSHReceivePackServer struct {
	grpc.ServerStream
}

func (x *sSHReceivePackServer) Send(m *GREResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *sSHReceivePackServer) Recv() (*GRERequest, error) {
	m := new(GRERequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _SSH_serviceDesc = grpc.ServiceDesc{
	ServiceName: "storage.SSH",
	HandlerType: (*SSHServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadPack",
			Handler:       _SSH_UploadPack_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ReceivePack",
			Handler:       _SSH_ReceivePack_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/storage/storage.proto",
}

func init() { proto.RegisterFile("pkg/storage/storage.proto", fileDescriptor_storage_d2d996bf7f0ca16a) }

var fileDescriptor_storage_d2d996bf7f0ca16a = []byte{
	// 810 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0x5b, 0x6f, 0xe2, 0x46,
	0x14, 0x96, 0xb9, 0x2e, 0x87, 0x6c, 0x76, 0x77, 0x96, 0x4d, 0xbd, 0x66, 0xb5, 0xa5, 0x56, 0x55,
	0xa1, 0x56, 0x82, 0x85, 0x95, 0x56, 0x95, 0xd2, 0x97, 0x84, 0x20, 0x12, 0x29, 0x95, 0xa2, 0x49,
	0xfb, 0x1c, 0x19, 0xfb, 0x04, 0xdc, 0x80, 0xc7, 0xf5, 0x0c, 0x55, 0x78, 0xeb, 0x4f, 0xea, 0xaf,
	0x68, 0xff, 0x56, 0x35, 0x37, 0x63, 0x08, 0x48, 0xd1, 0x3e, 0xf9, 0x9c, 0x6f, 0xce, 0x65, 0xbe,
	0x39, 0x17, 0xc3, 0xfb, 0xf4, 0x61, 0xd6, 0xe7, 0x82, 0x65, 0xc1, 0x0c, 0xed, 0xb7, 0x97, 0x66,
	0x4c, 0x30, 0x52, 0x37, 0xaa, 0xd7, 0x9e, 0x31, 0x36, 0x5b, 0x60, 0x5f, 0xc1, 0xd3, 0xd5, 0x7d,
	0x1f, 0x97, 0xa9, 0x58, 0x6b, 0x2b, 0xff, 0x0b, 0x90, 0x11, 0x5b, 0x2e, 0x63, 0x31, 0x62, 0xab,
	0x44, 0x50, 0xfc, 0x73, 0x85, 0x5c, 0x90, 0x63, 0x28, 0xc5, 0x91, 0xeb, 0x74, 0x9c, 0x6e, 0x83,
	0x96, 0xe2, 0x88, 0xbc, 0x86, 0x72, 0x86, 0xf7, 0x6e, 0x49, 0x01, 0x52, 0xf4, 0xef, 0xe0, 0x8d,
	0xf6, 0xbb, 0x8e, 0xf9, 0xf3, 0xdd, 0x48, 0x0b, 0xaa, 0x8b, 0x78, 0x19, 0x0b, 0xb7, 0xdc, 0x71,
	0xba, 0x65, 0xaa, 0x15, 0x42, 0xa0, 0xc2, 0x1f, 0xe2, 0xd4, 0xad, 0x28, 0x50, 0xc9, 0xfe, 0xc4,
	0x5e, 0x4c, 0x27, 0xe0, 0x29, 0x4b, 0x38, 0x92, 0x01, 0xd4, 0x43, 0x85, 0x72, 0xd7, 0xe9, 0x94,
	0xbb, 0xcd, 0xe1, 0x37, 0x3d, 0xcb, 0x5a, 0x5b, 0x5b, 0x4b, 0x6a, 0xed, 0xfc, 0x9f, 0xe0, 0xed,
	0x16, 0x43, 0x13, 0xa9, 0x05, 0xd5, 0x50, 0x02, 0xea, 0xba, 0x65, 0xaa, 0x15, 0x7f, 0x08, 0x30,
	0xa1, 0xe3, 0x43, 0x7c, 0x5a, 0x50, 0xe5, 0x22, 0x8a, 0x13, 0xc5, 0xe8, 0x88, 0x6a, 0xc5, 0x4f,
	0xa1, 0xa9, 0x7c, 0x4c, 0xe0, 0x13, 0xa8, 0x71, 0x11, 0xb1, 0x95, 0x8e, 0x7c, 0x44, 0x8d, 0x66,
	0x70, 0xcc, 0x32, 0xe3, 0x6d, 0x34, 0x32, 0x80, 0x06, 0x3e, 0xc6, 0xe2, 0x2e, 0x64, 0x11, 0xaa,
	0x67, 0x69, 0x0e, 0x5b, 0x39, 0xa9, 0x09, 0x1d, 0x8f, 0x1f, 0xe5, 0xd5, 0x23, 0xa4, 0x2f, 0xd0,
	0x48, 0xfe, 0x8f, 0x2a, 0xa3, 0x3d, 0x20, 0xed, 0x62, 0x04, 0x99, 0xb4, 0x5a, 0xb0, 0xfd, 0x16,
	0x5e, 0x8e, 0x32, 0x0c, 0x04, 0x1e, 0x20, 0xe5, 0x5f, 0xc1, 0xbb, 0x5b, 0x14, 0x17, 0xc8, 0xc3,
	0x2c, 0x4e, 0x45, 0xcc, 0x92, 0x43, 0xec, 0x3b, 0xd0, 0x8c, 0x36, 0x56, 0xa6, 0xaa, 0x45, 0xc8,
	0xff, 0x0e, 0x5e, 0x9d, 0x67, 0x41, 0x12, 0xce, 0x91, 0x1f, 0xca, 0x76, 0x0d, 0xc7, 0xda, 0x24,
	0x7f, 0x2f, 0x02, 0x95, 0x24, 0x58, 0xa2, 0xb1, 0x51, 0xb2, 0x6a, 0x88, 0x79, 0x30, 0x30, 0x39,
	0x94, 0x2c, 0x31, 0xb1, 0x4e, 0xf5, 0x13, 0x35, 0xa8, 0x92, 0xfd, 0x11, 0xbc, 0xde, 0x24, 0x34,
	0xf1, 0xfa, 0x50, 0x9b, 0x2a, 0xec, 0x49, 0x87, 0x6c, 0x27, 0xa6, 0xc6, 0xcc, 0x1f, 0xc0, 0x4b,
	0xdb, 0x3b, 0xcf, 0xed, 0xfe, 0x7f, 0x4a, 0x70, 0xbc, 0xdd, 0x6f, 0xf2, 0x7a, 0x97, 0x01, 0x9f,
	0x5b, 0x1a, 0x52, 0x96, 0xd8, 0x6f, 0x19, 0xa2, 0xa5, 0x21, 0x65, 0xd9, 0x06, 0x37, 0x41, 0x86,
	0x89, 0x30, 0x44, 0x8c, 0x46, 0x5c, 0xa8, 0xff, 0x8a, 0x9c, 0x07, 0x33, 0x54, 0x63, 0xd0, 0xa0,
	0x56, 0x95, 0x1e, 0x67, 0x2b, 0x31, 0x67, 0x99, 0x5b, 0xd5, 0x1e, 0x5a, 0x93, 0xf5, 0xd0, 0xd2,
	0x78, 0x19, 0xc4, 0x0b, 0xb7, 0xa6, 0xeb, 0x51, 0x80, 0xc8, 0x47, 0x00, 0xad, 0x5e, 0x04, 0x02,
	0xdd, 0xba, 0x6a, 0xf4, 0x02, 0x42, 0x3e, 0x40, 0x43, 0xb3, 0x10, 0x98, 0xb9, 0x2f, 0x94, 0xff,
	0x06, 0x20, 0x3f, 0x58, 0x8e, 0x02, 0x4d, 0x8a, 0x86, 0x32, 0xd9, 0x41, 0xc9, 0xf7, 0xf6, 0xfd,
	0x04, 0xea, 0x44, 0xa0, 0x12, 0x6d, 0x83, 0xfe, 0x08, 0x9a, 0x92, 0xff, 0xf3, 0x57, 0x05, 0x81,
	0x4a, 0x1a, 0x88, 0xb9, 0xad, 0xb7, 0x94, 0xfd, 0x19, 0xbc, 0x91, 0x41, 0xc6, 0x89, 0xc8, 0xd6,
	0xc5, 0x97, 0x5f, 0xda, 0xce, 0x6f, 0x50, 0x25, 0xe7, 0xcd, 0x52, 0xda, 0x34, 0x8b, 0x7c, 0x47,
	0x36, 0xfd, 0x03, 0xc3, 0xfc, 0xe5, 0xb5, 0x96, 0x27, 0xaa, 0x14, 0x12, 0x5d, 0xc3, 0x91, 0xbe,
	0xad, 0xc9, 0xf1, 0x0b, 0x34, 0x85, 0x49, 0x1c, 0xa3, 0xdd, 0x3d, 0x5e, 0xde, 0x59, 0x4f, 0x2e,
	0x45, 0x8b, 0xe6, 0xc3, 0x7f, 0x1d, 0x00, 0x8a, 0x29, 0xe3, 0xb1, 0x60, 0xd9, 0x9a, 0xfc, 0x0c,
	0x35, 0x3d, 0x92, 0xe4, 0x64, 0xb3, 0xbd, 0x8a, 0x33, 0xea, 0x9d, 0xf4, 0xf4, 0xce, 0xee, 0xd9,
	0x9d, 0xdd, 0x1b, 0xcb, 0x9d, 0x4d, 0xae, 0xe0, 0xd5, 0xf6, 0xac, 0x72, 0xf2, 0x31, 0x0f, 0xb1,
	0x77, 0x8a, 0x0f, 0x86, 0xfa, 0xac, 0x7b, 0x93, 0xb4, 0xb6, 0x48, 0x58, 0xaf, 0x77, 0x3b, 0xa8,
	0x66, 0x35, 0x1c, 0x43, 0x4d, 0x0f, 0x11, 0x39, 0x85, 0x8a, 0x5c, 0xcc, 0xc4, 0xdd, 0x99, 0xae,
	0x7c, 0xf2, 0xbd, 0xf7, 0x7b, 0x4e, 0x4c, 0x98, 0xff, 0x1c, 0xa8, 0xe9, 0xee, 0x20, 0xe7, 0x50,
	0x55, 0x7b, 0x99, 0xb4, 0x77, 0x16, 0x79, 0xf1, 0x7f, 0xe4, 0x7d, 0xd8, 0x7f, 0x68, 0x8a, 0x73,
	0x66, 0xee, 0xe2, 0xed, 0x58, 0x15, 0x7e, 0x4d, 0x5e, 0x7b, 0xef, 0x99, 0x0e, 0xf0, 0xc9, 0x21,
	0x5f, 0xa0, 0x3c, 0x41, 0x51, 0xac, 0x47, 0x71, 0x23, 0x78, 0x87, 0xfe, 0x32, 0xc3, 0xbf, 0x1d,
	0x28, 0xdf, 0xde, 0x5e, 0x92, 0x53, 0x80, 0xdf, 0xd3, 0x05, 0x0b, 0xa2, 0x9b, 0x20, 0x7c, 0x20,
	0x6f, 0x8b, 0xfb, 0xdb, 0xc6, 0x68, 0x6d, 0x83, 0x3a, 0x40, 0xd7, 0xf9, 0xe4, 0xc8, 0xe6, 0xa2,
	0x18, 0x62, 0xfc, 0x17, 0x7e, 0x85, 0xf7, 0xb4, 0xa6, 0x0a, 0xfb, 0xf9, 0xff, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x21, 0x2c, 0x23, 0xee, 0x0b, 0x08, 0x00, 0x00,
}
