// Code generated by go-swagger; DO NOT EDIT.

package repositories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
)

// NewCreateRepositoryParams creates a new CreateRepositoryParams object
// no default values defined in spec.
func NewCreateRepositoryParams() CreateRepositoryParams {

	return CreateRepositoryParams{}
}

// CreateRepositoryParams contains all the bound params for the create repository operation
// typically these are obtained from a http.Request
//
// swagger:parameters createRepository
type CreateRepositoryParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The repository to create
	  Required: true
	  In: body
	*/
	NewRepository CreateRepositoryBody
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewCreateRepositoryParams() beforehand.
func (o *CreateRepositoryParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body CreateRepositoryBody
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("newRepository", "body"))
			} else {
				res = append(res, errors.NewParseError("newRepository", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.NewRepository = body
			}
		}
	} else {
		res = append(res, errors.Required("newRepository", "body"))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
