// Code generated by go-swagger; DO NOT EDIT.

package repositories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	errors "github.com/go-openapi/errors"
	middleware "github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	swag "github.com/go-openapi/swag"
	validate "github.com/go-openapi/validate"
)

// CreateRepositoryHandlerFunc turns a function with the right signature into a create repository handler
type CreateRepositoryHandlerFunc func(CreateRepositoryParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateRepositoryHandlerFunc) Handle(params CreateRepositoryParams) middleware.Responder {
	return fn(params)
}

// CreateRepositoryHandler interface for that can handle valid create repository params
type CreateRepositoryHandler interface {
	Handle(CreateRepositoryParams) middleware.Responder
}

// NewCreateRepository creates a new http.Handler for the create repository operation
func NewCreateRepository(ctx *middleware.Context, handler CreateRepositoryHandler) *CreateRepository {
	return &CreateRepository{Context: ctx, Handler: handler}
}

/*CreateRepository swagger:route POST /repositories repositories createRepository

Create a new repository

*/
type CreateRepository struct {
	Context *middleware.Context
	Handler CreateRepositoryHandler
}

func (o *CreateRepository) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateRepositoryParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// CreateRepositoryBody create repository body
// swagger:model CreateRepositoryBody
type CreateRepositoryBody struct {

	// description
	Description string `json:"description,omitempty"`

	// name
	// Required: true
	Name *string `json:"name"`

	// website
	Website string `json:"website,omitempty"`
}

// Validate validates this create repository body
func (o *CreateRepositoryBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CreateRepositoryBody) validateName(formats strfmt.Registry) error {

	if err := validate.Required("newRepository"+"."+"name", "body", o.Name); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *CreateRepositoryBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateRepositoryBody) UnmarshalBinary(b []byte) error {
	var res CreateRepositoryBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
