// Code generated by go-swagger; DO NOT EDIT.

package repositories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/gitpods/gitpods/internal/api/v1/models"
)

// GetRepositoryOKCode is the HTTP code returned for type GetRepositoryOK
const GetRepositoryOKCode int = 200

/*GetRepositoryOK The repository found by its owner and name

swagger:response getRepositoryOK
*/
type GetRepositoryOK struct {

	/*
	  In: Body
	*/
	Payload *models.Repository `json:"body,omitempty"`
}

// NewGetRepositoryOK creates GetRepositoryOK with default headers values
func NewGetRepositoryOK() *GetRepositoryOK {

	return &GetRepositoryOK{}
}

// WithPayload adds the payload to the get repository o k response
func (o *GetRepositoryOK) WithPayload(payload *models.Repository) *GetRepositoryOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get repository o k response
func (o *GetRepositoryOK) SetPayload(payload *models.Repository) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRepositoryOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
