// Code generated by go-swagger; DO NOT EDIT.

package repositories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/gitpods/gitpods/internal/api/v1/models"
)

// GetOwnerRepositoriesOKCode is the HTTP code returned for type GetOwnerRepositoriesOK
const GetOwnerRepositoriesOKCode int = 200

/*GetOwnerRepositoriesOK The repositories found by its owner name

swagger:response getOwnerRepositoriesOK
*/
type GetOwnerRepositoriesOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Repository `json:"body,omitempty"`
}

// NewGetOwnerRepositoriesOK creates GetOwnerRepositoriesOK with default headers values
func NewGetOwnerRepositoriesOK() *GetOwnerRepositoriesOK {

	return &GetOwnerRepositoriesOK{}
}

// WithPayload adds the payload to the get owner repositories o k response
func (o *GetOwnerRepositoriesOK) WithPayload(payload []*models.Repository) *GetOwnerRepositoriesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get owner repositories o k response
func (o *GetOwnerRepositoriesOK) SetPayload(payload []*models.Repository) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOwnerRepositoriesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Repository, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
