// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi GitPods OpenAPI
This is the API for GitPods - git in the cloud.


    Schemes:
      http
      https
    Host: localhost
    BasePath: /v1
    Version: 1.0.0
    License: Apache-2.0 http://www.apache.org/licenses/LICENSE-2.0.html

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
